### ISSUE TITLE
O programa fecha sozinho

### ISSUE THREAD

**Issue by ghost** [terroo/img2txt#1]
Estou usando o arch linux gui plasma e conseguir instalar o img2txt mais na hora de abrir qualquer imagem pelo programa ele fecha sozinho. Não sou um usuário avançado e não sei o que está acontecendo.

aparece isso no terminal:

[luiz@luiz-dellprecisionm3800 ~]$ sudo img2txt

QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
Error opening data file /usr/share/tessdata/por.traineddata
Please make sure the TESSDATA_PREFIX environment variable is set to your "tessdata" directory.
Failed loading language 'por'
Tesseract couldn't load any languages!
Estimating resolution as 387
/usr/local/bin/img2txt, linha 3: 18210 Falha de segmentação  (imagem do núcleo gravada)/opt/img2txt/Img2Txt

**Comment by terroo** [comment]
Provavelmente você não tem o tesseract-ocr-por . Também evite usar com sudo

**Comment by ghost** [comment]
> você sabe como instalar o tesseract-ocr-por no ubuntu 22.04

Conseguir instalar o tesseract mais não tesseract-ocr-por

**Comment by terroo** [comment]
Acho que no Arch ele é referenciado por outro nome, tente: 
 [tesseract-data-por](https://archlinux.org/packages/community/any/tesseract-data-por/)

**Comment by ghost** [comment]
Muito obrigado conseguir
